### ISSUE TITLE
not working in slack rss feed 

### ISSUE THREAD

**Issue by zsaladin** [capjamesg/hugging-face-papers-rss#3]
I added the rss feed by slack command below

```
/feed subscribe https://jamesg.blog/hf-papers.xml
```

But nothing happens during several days.
As far as I know one of recent posts should be pop up instantly in the slack channel when the feed is added if the subscription is valid.

I noticed that the `<author>` element is invalid. See following address
- https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fjamesg.blog%2Fhf-papers.xml

Or could anyone explain how to fix it?

**Comment by capjamesg** [comment]
Hello there! I will take a look to see what's going on and report back here.

**Comment by capjamesg** [comment]
The missing author shouldn't stop feeds from being able to subscribe. Can you try to re-subscribe and see what happens? I pushed a change today that fixes a few things.

**Comment by zsaladin** [comment]
Sorry for late response.

It still not work.
I tried it with other rss reader and it was successful.
So this may be an integration issue with slack.

[RSS app](https://slack.com/marketplace/A0F81R7U7-rss) is provided by slack team so I can't see any logs.
According to the [guide](https://slack.com/help/articles/218688467-Add-RSS-feeds-to-Slack) they suggest to use [validator](http://validator.w3.org/feed/) if you got an error.

So I attach the validation error link

**Comment by isnbh0** [comment]
After the update in #4 I got the Slack feed reader to work. @zsaladin Can you check on your end? If it works, I think we can close this issue as resolved 🙂

**Comment by zsaladin** [comment]
@isnbh0 

It's working now!! Thank you for the contribution!!!
